### ISSUE TITLE
Running into MySQL Row size too large when trying to update to 1.0.4

### ISSUE THREAD

**Issue by webmarks** [elivz/VzUrl-Craft#11]
I tried upgrading to 1.0.4 and it failed. I think the issue I'm experiencing has to do with a large number of VZ URL fields on that install. 

It seems to be bumping into the maximum row size of 65K in the craft_content table when the migration code attempts to change all VARCHAR fields from 255 to 2000.

**Comment by elivz** [comment]
Okay, I decided to switch it to a TEXT column, which doesn't count towards the row limit. If you install v1.0.5, it should upgrade successfully for you!

**Comment by webmarks** [comment]
Yes, the new update worked smoothly. Thank you!
