### ISSUE TITLE
Hitting row limit when converting fields from Plain text to VzUrl

### ISSUE THREAD

**Issue by fantasticmachine** [elivz/VzUrl-Craft#13]
Just ran into an interesting problem when converting some Plain Text fields to use VzURL.

There are 14 fields which I was converting. All was well up until around number 10. When I attempted to change that one I got the following error.

`CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. You have to change some columns to TEXT or BLOBs. The SQL statement executed was: ALTER TABLE `craft_content` CHANGE `field_tool` `field_tool` VARCHAR(2000) NULL` 

I went ahead and changed the remaining fields by directly altering the craft_fields table itself and all seems to work OK.

As a further test, I changed one of the fields back to Plain text via the CP. Then back to VzUrl - I got the same problem.

**Comment by elivz** [comment]
Try the current version. I did something dumb – I was setting the column to a STRING initially and then migrating it to a TEXT column. I changed so it starts as a TEXT column, so you shouldn't run into the row length problem any more.

**Comment by fantasticmachine** [comment]
Tried the latest version and getting this error
`Fatal error: Undefined class constant 'Text' in /project/path/build/craft/plugins/vzurl/fieldtypes/VzUrlFieldType.php on line 16`

**Comment by elivz** [comment]
Ugh, fixed now.

**Comment by fantasticmachine** [comment]
Works a treat!
