### ISSUE TITLE
Validate "#"

### ISSUE THREAD

**Issue by lindseydiloreto** [elivz/VzUrl-Craft#3]
Awesome plugin, thanks for building it! :)

I've noticed that URLs which use a hash don't validate... Can this be fixed? It's very common to put in some temporary links until the proper URL is put in place.

This URL should be considered valid:

    #

**Comment by elivz** [comment]
Good point (and sorry for the delayed response - I've been traveling). I have changed it so URLs starting with either '#' and '?' - i.e. links that are relative to the current URL - are always considered valid.

**Comment by lindseydiloreto** [comment]
Sweet, thank you!
