### ISSUE TITLE
JSON warning

### ISSUE THREAD

**Issue by robzor** [elivz/VzUrl-Craft#5]
Hi there,

Love the plug-in but just wanted to give you a heads up about an issue in the Craft Log:

`The “VZ URL” plugin release feed didn’t come back as valid JSON:`

Obviously not a showstopper, but hopefully an easy fix :)

**Comment by elivz** [comment]
Thanks for the heads-up! I will resolve this in the next version.

**Comment by bossanova808** [comment]
If people want to get rid of these errors in the meantime (since Craft dumps the entire github html file into the log ?!), you can put:

`https://raw.githubusercontent.com/elivz/VzUrl-Craft/master/changelog.json`

..in as the url instead in the main plugin file - i.e. change it to:

```
    public function getReleaseFeedUrl()
    {
        return 'https://raw.githubusercontent.com/elivz/VzUrl-Craft/master/changelog.json';
    }
}
```

**Comment by elivz** [comment]
Sorry about that...I thought I had fixed this, but obviously not. Just pushed a minor update with the correct release URL.
